# Generated by Django 3.0.7 on 2020-06-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cabaña',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('texto', models.TextField(max_length=500)),
                ('fecha', models.DateField()),
                ('imagen_link_1', models.CharField(max_length=100)),
                ('imagen_link_2', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_link_3', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_link_4', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_link_5', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_link_6', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_link_7', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_link_8', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
