# Generated by Django 3.0.7 on 2020-06-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maria_irma_app', '0002_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabaña',
            name='imagen_link_1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cabaña',
            name='imagen_link_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cabaña',
            name='imagen_link_3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cabaña',
            name='imagen_link_4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cabaña',
            name='imagen_link_5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cabaña',
            name='imagen_link_6',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cabaña',
            name='imagen_link_7',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cabaña',
            name='imagen_link_8',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
