# Generated by Django 3.0.7 on 2020-06-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maria_irma_app', '0003_auto_20200615_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='cabana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('texto', models.TextField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('image_main', models.ImageField(upload_to='cabanas/')),
                ('image_1', models.ImageField(upload_to='cabanas/')),
                ('image_2', models.ImageField(upload_to='cabanas/')),
                ('image_3', models.ImageField(upload_to='cabanas/')),
                ('image_4', models.ImageField(upload_to='cabanas/')),
                ('image_5', models.ImageField(upload_to='cabanas/')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='cabaña',
        ),
        migrations.DeleteModel(
            name='plano',
        ),
    ]
