# Generated by Django 3.0.7 on 2020-06-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maria_irma_app', '0005_auto_20200623_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabana',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='cabanas/', verbose_name='Imagen 1'),
        ),
        migrations.AlterField(
            model_name='cabana',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='cabanas/', verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='cabana',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='cabanas/', verbose_name='Imagen 3'),
        ),
        migrations.AlterField(
            model_name='cabana',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='cabanas/', verbose_name='Imagen 4'),
        ),
        migrations.AlterField(
            model_name='cabana',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='cabanas/', verbose_name='Imagen 5'),
        ),
    ]
