# Generated by Django 3.0.7 on 2020-06-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maria_irma_app', '0008_auto_20200623_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('texto', models.TextField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('image_main', models.ImageField(upload_to='planos/', verbose_name='Imagen principal')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='planos/', verbose_name='Imagen 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='planos/', verbose_name='Imagen 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='planos/', verbose_name='Imagen 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='planos/', verbose_name='Imagen 4')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='planos/', verbose_name='Imagen 5')),
            ],
        ),
    ]
