# Generated by Django 3.0.7 on 2020-07-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maria_irma_app', '0009_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabana',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='cabanas/', verbose_name='Imagen 5 (La foto más grande)'),
        ),
        migrations.AlterField(
            model_name='cabana',
            name='image_main',
            field=models.ImageField(upload_to='cabanas/', verbose_name='Imagen principal (Primera a ver)'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='planos/', verbose_name='Imagen 5 (La foto más grande)'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='image_main',
            field=models.ImageField(upload_to='planos/', verbose_name='Imagen principal (Primera a ver)'),
        ),
    ]
